package com.example.android;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.android.Cookie;

import com.example.android.CookieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cookieDaoConfig;

    private final CookieDao cookieDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cookieDaoConfig = daoConfigMap.get(CookieDao.class).clone();
        cookieDaoConfig.initIdentityScope(type);

        cookieDao = new CookieDao(cookieDaoConfig, this);

        registerDao(Cookie.class, cookieDao);
    }
    
    public void clear() {
        cookieDaoConfig.getIdentityScope().clear();
    }

    public CookieDao getCookieDao() {
        return cookieDao;
    }

}
